---
title: "School Expenses"
author: "Jeff Huang"
date: "4/27/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
library(janitor)
library(ggplot2)
library(gt)
library(reshape2)
library(ggthemes)
```

```{r download, include=FALSE, echo=FALSE, message=FALSE, warning=FALSE}

# SAT download data

sat16 <- read_xls("data/sat16.xls") %>% 
  clean_names() %>% 
  select(-year)
sat15 <- read_xls("data/sat15.xls") %>% 
  clean_names()

# ACT download data

act18 <- read_xls("data/act18.xls") %>% 
  clean_names() %>% 
  mutate_at(9:14, as.integer) %>% 
  select(-year)
act17 <- read_xls("data/act17.xls") %>% 
  clean_names() %>% 
  mutate_at(9:14, as.integer)
act16 <- read_xls("data/act16.xls") %>% 
  clean_names() %>% 
  mutate_at(6:11, as.integer)
act15 <- read_xls("data/act15.xls") %>% 
  clean_names() %>% 
  mutate_at(6:11, as.integer) %>% 
  select(-year)

# AP scores download data

ap18 <- read_xls("data/ap18.xls") %>% 
  clean_names() %>% 
  select(-year) %>% 
  mutate_at(9:16, as.integer)

ap17 <- read_xls("data/ap17.xls") %>% 
  clean_names() %>% 
  mutate_at(9:16, as.integer)

ap16 <- read_xls("data/ap16.xls") %>% 
  clean_names() %>% 
  select(-year) %>% 
  mutate_at(6:13, as.integer)
ap15 <- read_xls("data/ap15.xls") %>% 
  clean_names() %>% 
  select(-year) %>% 
  mutate_at(6:13, as.integer)

# per district expenses data — clean data to merge later

expense18 <- read_xlsx("data/expense18.xlsx",
                       skip = 10) %>% 
  mutate(CDS = as.character(CDS)) %>% 
  clean_names()
expense17 <- read_xlsx("data/expense17.xlsx",
                       skip = 8) %>% 
  clean_names()
expense16 <- read_xls("data/expense16.xls", 
                      skip = 7) %>% 
  clean_names
expense15 <- read_xls("data/expense15.xls",
                      skip = 7) %>% 
  clean_names() %>% 
  rename(edp_365 = expenditures_edp_365) 



# Teacher Pay
# teacher stats of most efficient school districts
# $61-74K - avg teacher salary

walnut <- read_csv("data/walnut-2017.csv") %>% 
  clean_names() %>% 
  filter(str_detect(tolower(job_title), "teacher"))

tc <- read_csv("data/temple-city-2017.csv") %>% 
  clean_names() %>% 
  filter(str_detect(tolower(job_title), "teacher"))
  
op <- read_csv("data/oak-park-2017.csv") %>% 
  clean_names() %>% 
  filter(str_detect(tolower(job_title), "teacher"))

full_salary <- read_csv("data/salaries15.csv") %>% 
  clean_names() 

# free and reduced lunch - get free reduced lunch %  and enrollments and district code

frlunch <- read_xlsx("frlunch1819.xlsx", skip=1) %>% 
  clean_names()

# staff demographics - teacher/student ratio, teachers with advanced degrees, age, years teaching, years_in_district

staff <- read_tsv("StaffDemo17.txt") %>% 
  clean_names()


```


```{r top3_cleaning}

# Cleaning data for most efficient schools: aggregate to the district averages

walnut_tsal <- walnut %>% 
  rename(District = agency) %>% 
  group_by(District) %>% 
  summarize(total = mean(total_pay_benefits), base = mean(base_pay))

tc_tsal <- tc %>% 
  rename(District = agency) %>% 
  group_by(District) %>% 
  summarize(total = mean(total_pay_benefits), base = mean(base_pay))

op_tsal <- op %>% 
  rename(District = agency) %>% 
  group_by(District) %>% 
  summarize(total = mean(total_pay_benefits), base = mean(base_pay))

addtl_schools <- bind_rows(walnut_tsal, tc_tsal, op_tsal)


# full salary data cleaning

full_salary <- full_salary %>% 
  rename(ada = average_daily_attendance, avg_salary = avg_salary_2014_15)


# free and reduced lunch data cleaning: calculate free and reduced lunch percentages

frlunch_rate <- frlunch %>% 
  mutate(district_code = paste(county_code, district_code, sep="")) %>% 
  group_by(district_code) %>% 
  summarize(free_count = sum(free_meal_count_k_12), frpm_count = sum(frpm_count_k_12), enrollment = sum(enrollment_k_12)) %>% 
  mutate(free_rate = free_count/enrollment, frpm_rate = frpm_count/enrollment) %>% 
  select(district_code, enrollment, free_rate, frpm_rate)
  
# staff demographic info - split total number of staff members
# staff education currently arranged as one column, need it to spread, and contain counts

total <- staff %>% 
  group_by(district_code) %>% 
  mutate(total = n()) %>% 
  select(1:5, 17)

staff_edu <- staff %>% 
  group_by(district_code, education_level) %>% 
  summarize(count = n()) %>% 
  spread(key=education_level, value=count) %>% 
  ungroup()
  
new_staff <- left_join(total, staff_edu, by="district_code") %>% 
  distinct(district_code, .keep_all=TRUE) 

# calculate percentages of each degree

n_edu_staff <- new_staff %>% 
  mutate(bachelor = B+C, doctor = D, master = M + V, bach_per = bachelor / total, doc_per = D / total, mast_per = master/total) %>% 
  select(district_code, county_name, district_name, bachelor, doctor, master, bach_per, doc_per, mast_per) 

# staff demographic characteristics
# teachers defined as greater than 60% of time spent teaching (looking for teachers that do not do admin work)
# admin defined as greater than 40% as administrative work  (looking for admins that do not teach)
# aggregate across districts

count_teach <- staff %>% 
  filter(fte_teaching > 60) %>% 
  group_by(district_code) %>% 
  summarize(teacher = n())

count_admin <- staff %>% 
  filter(fte_administrative > 40) %>% 
  group_by(district_code) %>% 
  summarize(admin = n())

# summarize statistics of demographics for each district, join other tables

add_staff <- staff %>% 
  select(district_code, county_name, 
       district_name, age, education_level, 
       years_teaching, years_in_district, fte_teaching, fte_administrative, fte_pupil_services) %>% 
  group_by(district_code) %>% 
  summarize(avg_t_age = mean(age), t_exp = mean(years_teaching), dist_exp = mean(years_in_district), num_staff = n()) %>% 
  full_join(count_admin, by="district_code") %>% 
  full_join(count_teach, by="district_code")


# full staff addtl info

full_staff <- full_join(n_edu_staff, add_staff, by="district_code") %>% 
  full_join(frlunch_rate, b="district_code")


# merge/clean SAT dataset - numeric handling of data instead of character

full_sat <- bind_rows(sat15, sat16, .id="year")
full_sat[, 7:11] <- sapply(full_sat[, 7:11], as.numeric)

# compute average composite scores, as well as prepares for data merging

full_sat <- full_sat %>%
  mutate(sat_comp = avg_scr_read + avg_scr_math,
         sat_score = num_tst_takr * sat_comp,
         district_code = substr(cds, 1, 7)) %>% 
  select(1:8, sat_comp, sat_score, district_code, -rtype) %>% 
  drop_na(sat_comp, sat_score)

# merge AP dataset
# also adding numbers of tests taken, as well as average AP score

full_ap <- bind_rows(ap15, ap16, ap17, ap18, .id="year") %>%
  mutate(num_tst = num_scr1 + num_scr2 + num_scr3 + num_scr4 + num_scr5,
         score = num_scr1 * 1 + num_scr2 * 2 + num_scr3 * 3 + num_scr4 * 4 + num_scr5 * 5,
         district_code = substr(cds, 1, 7)) %>% 
  select(1:8, num_tst, score, district_code, -rtype) %>% 
  drop_na(score, num_tst)


# create composite scores by averaging each of the different scores, and create a "score" variable representing total score (to be added and divided at the district level later)

full_act <- bind_rows(act15, act16, act17, act18, .id="year") %>% 
  drop_na(sname, enroll12) %>% 
  mutate(comp = (avg_scr_eng + avg_scr_math + avg_scr_read + avg_scr_sci)/4, 
         score = comp * num_tst_takr,
         district_code = substr(cds, 1, 7)) %>% 
  mutate(test_per = num_tst_takr / enroll12) %>%
  select(1:8, comp, score, test_per, district_code, -rtype)



# district ranks. make sure that there are sufficient test takers (to prevent large outliers). Create a participation rate by dividing num of ACT test takers by 12th grade enrollment. not an meaningful rate by itself (all grades take the test), but it is a proxy for how many students are in a school, and how many take the test. used a percentile rank to avoid minor errors in this methodology

# same thing for the SAT and AP tests, although AP tests are divided by 10-12th grade enrollment because AP tests are much more commonly taken across grades than are SAT and ACT tests.
# create ranks for participation and composite score for merging later

district_act <- full_act %>% 
  drop_na(test_per, comp) %>% 
  group_by(district_code, dname) %>% 
  summarize(act_test_per = mean(num_tst_takr)/mean(enroll12), act_avg_comp = sum(score)/sum(num_tst_takr)) %>%
  ungroup() %>% 
  mutate(act_part_rank = ntile(act_test_per, 100), act_comp_rank = ntile(act_avg_comp, 100))

district_sat <- full_sat %>% 
  group_by(district_code, dname) %>% 
  summarize(sat_test_per = mean(num_tst_takr)/mean(enroll12), sat_avg_comp = sum(sat_score)/sum(num_tst_takr)) %>%
  ungroup() %>% 
  mutate(sat_part_rank = ntile(sat_test_per, 100), sat_comp_rank = ntile(sat_avg_comp, 100))

district_ap <- full_ap %>%
  group_by(district_code, dname) %>% 
  summarize(ap_test_per = mean(num_tst)/mean(enroll1012), ap_avg_score = sum(score)/sum(num_tst)) %>%
  ungroup() %>% 
  mutate(ap_part_rank = ntile(ap_test_per, 100), ap_score_rank = ntile(ap_avg_score, 100))



## expense data. binding 4 year averages of expenses. I wanted to use average daily attendance (current_expense_ada) to come up with a number of dollars spent per pupil according to days attended in school.

full_expense <- bind_rows(expense15, expense16, expense17, expense18, .id="year") %>% 
  filter(! district %in% c("Statewide", "Statewide Totals")) %>%
  filter(lea_type == "Unified") %>% 
  mutate(district_code = paste(co, cds, sep="")) %>% 
  group_by(district_code, district) %>% 
  summarize(d_spend = sum(current_expense_per_ada)/ 4) %>% 
  ungroup() %>% 
  mutate(expense_rank = ntile(desc(d_spend), 100))

# merged all test data

district <- full_join(district_sat, district_act, by="district_code") %>% 
  full_join(district_ap, by="district_code")

# merged the test and expense to perform more analysis

district <- district %>% 
  inner_join(full_expense, by="district_code") %>% 
  select(-'dname.x', -'dname.y', -district)


```

```{r indexes}

# create indexes for sorting later

index <- district %>% 
  mutate(comp_index = ((sat_comp_rank + act_comp_rank + ap_score_rank) / 3),
         comp_rank = ntile(comp_index, 100),
         part_index = ((sat_part_rank + act_part_rank + ap_part_rank) / 3),
         part_rank = ntile(part_index, 100))
  
# create table with entire dataset, cleaned

full_district_demo <- full_join(index, full_staff, by=c("district_code", "dname" = "district_name")) %>% 
  left_join(full_salary, by=c("dname" = "district_name")) %>% 
  select(-county_name) %>% 
  drop_na(dname) %>% 
  distinct(dname, district_code, .keep_all=TRUE)


# creating tables for later - pick interesting ones - chose ACT because it is typically the more correlative with schooling (not income)

expense <- full_district_demo %>% 
  arrange(desc(d_spend)) %>% 
  drop_na(act_comp_rank) %>% 
  head(10)

comp <- full_district_demo %>% 
  arrange(desc(act_avg_comp)) %>% 
  head(10)


# metrics - creating the efficiency ranking, reorganizing for the table

efficiency <- full_district_demo %>% 
  drop_na(sat_avg_comp, act_avg_comp, sat_test_per, act_test_per) %>% 
  mutate(comp_rank = ntile(((sat_avg_comp +  act_avg_comp / 2) +  ap_avg_score)/ 2, 100),
         part_rank = ntile(((sat_test_per +  act_test_per / 2) +  ap_test_per)/ 2, 100)) %>% 
  
# creates the efficiency ranking using the averages computed above  
  
  mutate(efficiency_rank = (4/12) * comp_rank + (3/12) * part_rank + (5/12) * expense_rank) %>% 
  arrange(desc(efficiency_rank)) %>% 
  mutate(act_test_per = act_test_per * 100,
         sat_test_per = sat_test_per * 100,
         ap_test_per = ap_test_per * 100) %>% 
  rename(District = dname, "ACT Participation Rate"=act_test_per,
         "SAT Participation Rate" = sat_test_per,
         "AP Participation Rate" = ap_test_per,
         "Avg. SAT Composite Score" = sat_avg_comp, 
         "Avg. ACT Composite Score" = act_avg_comp,
         "Avg. AP Score" = ap_avg_score,
         "Participation Percentile Rank"=part_rank, 
         "Composite Percentile Rank" = comp_rank, 
         "Per Pupil Spend" = d_spend,
         "Spend Percentile Rank" = expense_rank,
         "Efficiency Index" = efficiency_rank) %>% 
  
# adds additional stats for the three most efficient schools
  
  left_join(addtl_schools, by="District") %>% 
  mutate(admin_ratio_per100 = admin * 100 / enrollment,
         admin_teach_per100 = admin * 100 / teacher)


# adds averages for all the school districts in the data to use as comparison in bar graphs

average <- efficiency %>% 
  summarize_all(mean, na.rm=TRUE) 

average$District <- "Average Values"

efficiency <- bind_rows(efficiency, average)


```

``` {r cleaning_graphs}

# clean data for display

most_eff <- efficiency %>% 
  select(-sat_part_rank, -act_part_rank, -ap_part_rank, -ap_score_rank, -act_comp_rank, -sat_comp_rank, -`Spend Percentile Rank`, -bachelor, -doctor, -master, -`Efficiency Index`, -comp_index, -part_index, -`Composite Percentile Rank`, -`Participation Percentile Rank`) 

top3 <- efficiency %>% 
  filter(District %in% c("Walnut Valley Unified", "Temple City Unified", "Oak Park Unified", "Average Values"))

top10 <- efficiency %>% 
  arrange(desc(`Efficiency Index`))


# editing for later graphs

eff_tsal <- top3 %>%
  select(District, total, base) %>%
  rename(`Base Salary` = base,
              `Total Salary (incl. Benefits)` = total) %>% 
  melt(id.vars = 'District')

eff_ratio <- top3 %>%
  mutate(admin_ratio_per100 = admin * 1000 / enrollment,
         admin_teach_per100 = admin * 100 / teacher) %>%
  select(District, admin_ratio_per100, admin_teach_per100) %>%
  rename(`Admin to Student Ratio (per 1,000)` = admin_ratio_per100,
              `Admin to Teacher Ratio (per 100)` = admin_teach_per100) %>% 
  melt(id.vars='District')

eff_adv <- top3 %>%
  select(District, bach_per, mast_per, doc_per) %>%
  rename(
    `Percent of Teachers with Bachelors'` = bach_per,
    `Percent of Teachers with Masters'` = mast_per,
    `Percent of Teachers with Doctorates'` = doc_per
  ) %>% 
  melt(id.vars='District')

eff_frpm <- top3 %>%
  select(District, free_rate, frpm_rate) %>%
  rename(`Percent of Students on Free Lunch` = free_rate,
         `Percent of Students on Free or Reduced Lunch` = frpm_rate) %>% 
  melt(id.vars="District")

eff_addtl <- top3 %>%
  select(District, avg_t_age, t_exp, dist_exp) %>%
  rename(     `Average Teacher Age` = avg_t_age,
              `Years of Teaching Experience` = t_exp,
              `Years in District` = dist_exp) %>% 
  melt(id.vars="District")

select_eff <- most_eff %>% arrange(District)



library(gt)
top10
top10 <- top10 %>% 
  select(District, `Spend Percentile Rank`, `Composite Percentile Rank`, `Participation Percentile Rank`, `Efficiency Index`) %>% 
  head(10)
  
gt(top10) %>% 
  tab_header(
    title= "Most Efficient CA School Districts") %>% 
  fmt_number(columns = c(2:5),
             decimals = 1)
```



``` {r write}

# writing files out

write_rds(full_district_demo, "full.rds")
write_rds(expense, "CA_EDUC_Data/expense.rds")
write_rds(comp, "CA_EDUC_Data/comp.rds")
write_rds(most_eff, "CA_EDUC_Data/efficiency.rds")
write_rds(top3, "CA_EDUC_Data/top3.rds")
write_rds(top10, "CA_EDUC_Data/top10.rds")
write_rds(eff_tsal, "CA_EDUC_Data/eff_tsal.rds")
write_rds(eff_ratio, "CA_EDUC_Data/eff_ratio.rds")
write_rds(eff_adv, "CA_EDUC_Data/eff_adv.rds")
write_rds(eff_frpm, "CA_EDUC_Data/eff_frpm.rds")
write_rds(eff_addtl, "CA_EDUC_Data/eff_addtl.rds")
write_rds(select_eff, "CA_EDUC_DATA/select_eff.rds")

```

